### ISSUE TITLE
Crash after unlock device

### ISSUE THREAD

**Issue by jpsember** [jpsember/cam#13]
FATAL EXCEPTION: main
Process: com.js.camera.cam, PID: 1921
java.lang.IllegalStateException: Camera not open
    at com.js.camera.MyCamera.assertOpen(MyCamera.java:149)
    at com.js.camera.MyCamera.getPreviewSizes(MyCamera.java:207)
    at com.js.camera.CameraPreview.calculatePreviewSize(CameraPreview.java:131)
    at com.js.camera.CameraPreview.onLayout(CameraPreview.java:66)
    at android.view.View.layout(View.java:15745)

**Comment by jpsember** [comment]
Build a fresh MyCamera object within onResume(), no earlier
