### ISSUE TITLE
App doesn't restart properly 

### ISSUE THREAD

**Issue by jpsember** [jpsember/cam#32]
No camera view appears.

**Comment by jpsember** [comment]
To reproduce: 

1) start app in landscape mode
2) turn off device (but leave plugged in)
3) rotate to portrait mode
4) turn device on

--------------- Start of MainActivity ----- 3:07:41 ------------- 

onResume 
--      PhotoFile PhotoFile:DOE, --: open() 
--      PhotoFile PhotoFile:DOE, --: Changing state from Start to Opening 
--      PhotoFile PhotoFile:DOE, (HandlerThread:EAT) --: backgroundThreadOpenFile 
--      PhotoFile PhotoFile:DOE, --: close() 
--      PhotoFile PhotoFile:DOE, (HandlerThread:EAT) --: Reading file state: {"randomseed":1,"nextid":14} 
--      PhotoFile PhotoFile:DOE, (HandlerThread:EAT) --: Opened root directory /storage/emulated/0/Android/data/com.js.camera.cam/files/Photos 
--      PhotoFile PhotoFile:DOE, --: Changing state from Opening to Open 
FATAL EXCEPTION: main
Process: com.js.camera.cam, PID: 13783
java.lang.NullPointerException
    at com.js.camera.MainActivity$2.stateChanged(MainActivity.java:135)
    at com.js.camera.PhotoFile$5.run(PhotoFile.java:246)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5479)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
    at dalvik.system.NativeStart.main(Native Method)
