### ISSUE TITLE
Sometimes taking a photo causes a crash

### ISSUE THREAD

**Issue by jpsember** [jpsember/cam#8]
Possibly related to : 

http://stackoverflow.com/questions/7942378/android-camera-will-not-work-startpreview-fails

Some output:

-- CameraPreview --: onLayout 
-- CameraPreview --: surfaceChanged(), camera.isOpen=T mPreviewSize=   1024     768 
--      MyCamera --: startPreview(); MyCamera state Open 
onPictureTaken - raw 
-- CameraPreview --: onMeasure, setMeasuredDimension to 0 x 0 
-- CameraPreview --: onMeasure, setMeasuredDimension to 874 x 760 
-- CameraPreview --: getOptimalPreviewSize, target     874     760 
-- CameraPreview --: sizes: [    1024     768    1024     576     800     480     640     480 ]  
-- CameraPreview --: set preview size to     800     480 
-- CameraPreview --: onLayout 
-- CameraPreview --: surfaceChanged(), camera.isOpen=T mPreviewSize=    800     480 
--      MyCamera --: startPreview(); MyCamera state Open 
FATAL EXCEPTION: main
Process: com.js.camera.cam, PID: 31365
java.lang.RuntimeException: startPreview failed
    at android.hardware.Camera.startPreview(Native Method)
    at com.js.camera.MyCamera.startPreview(MyCamera.java:99)
    at com.js.camera.CameraPreview.surfaceChanged(CameraPreview.java:114)
    at android.view.SurfaceView.updateWindow(SurfaceView.java:613)
    at android.view.SurfaceView.setFrame(SurfaceView.java:302)
    at android.view.View.layout(View.java:15741)
    at com.js.camera.CameraPreview.onLayout(CameraPreview.java:77)
    at android.view.View.layout(View.java:15745)
    at android.view.ViewGroup.layout(ViewGroup.java:4867)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)

**Comment by jpsember** [comment]
To recreate: click on the preview to cause it to take a photo; then quickly click on one of the ShrinkingViews.  This will trigger a layout, and a crash since the 'take photo' logic hasn't completed... or something related to that
